### ISSUE TITLE
40h error?

### ISSUE THREAD

**Issue by igormpc** [tehn/isms#1]
hi brian
trying isms here on arch linux --
first i had to add to Makefile line 14
-I/usr/include/libevdev-1.0
to find libevdev here

i can send osc to/from sc and listen PolyPerc but got an error 
(maybe because i'm using a 40h/led intensity? how can i fix it?):

thx in advance! :)

~/.local/share/isms
❯ isms example.lua
isms ////////
>> OSC port 10011
>> SOCKET port 11001
>>>> isms.run('example.lua')

>> isms.clear
example.lua -------------> hello there
3
test.lua
>> device scan
got ttyUSB, assuming grid
monome device appears to be a grid; rows=8; cols=8; quads=1
>> starting event loop
grid added:     1       monome 40h m40h1036     m40h1036
metro   1       1
/home/igor/.local/share/isms/system/grid.lua:93: attempt to index a number value (local 'self')
stack traceback:
        /home/igor/.local/share/isms/system/grid.lua:93: in function 'grid.all'
        example.lua:33: in function <example.lua:31>
isms.midi.add: 2, USB Midi        , userdata: 0x557c45453d00
metro   1       2
/home/igor/.local/share/isms/system/grid.lua:93: attempt to index a number value (local 'self')
stack traceback:
        /home/igor/.local/share/isms/system/grid.lua:93: in function 'grid.all'
        example.lua:33: in function <example.lua:31>
metro   1       3
/home/igor/.local/share/isms/system/grid.lua:93: attempt to index a number value (local 'self')
stack traceback:
        /home/igor/.local/share/isms/system/grid.lua:93: in function 'grid.all'
        example.lua:33: in function <example.lua:31>
metro   1       4
/home/igor/.local/share/isms/system/grid.lua:93: attempt to index a number value (local 'self')
stack traceback:
        /home/igor/.local/share/isms/system/grid.lua:93: in function 'grid.all'
        example.lua:33: in function <example.lua:31>
metro   1       5
/home/igor/.local/share/isms/system/grid.lua:93: attempt to index a number value (local 'self')
stack traceback:
        /home/igor/.local/share/isms/system/grid.lua:93: in function 'grid.all'
        example.lua:33: in function <example.lua:31>

**Comment by tehn** [comment]
hello! i'm not actively developing this project--- it's more of an
experiment. unless you're willing to get into the C code i wouldn't really
recommend this for much more than experimentation and curiosity.

yes, to get a monobright grid working you may need to tinker with the
libmonome integration. luckily the folder tree is laid out pretty well and
the code is minimal, so hopefully you can find your way if you're feeling
ambitious.

**Comment by tehn** [comment]
also i may have broken some of the lua by accident. i haven't checked grid integration (and this project in general) for quite some time
